// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvRIv7WNcjhv-g9v-iwvQmhNBBNueq6sM',
    appId: '1:670479563518:web:43e7115a4fb83a02b343af',
    messagingSenderId: '670479563518',
    projectId: 'cdac-vishing-project',
    authDomain: 'cdac-vishing-project.firebaseapp.com',
    storageBucket: 'cdac-vishing-project.appspot.com',
    measurementId: 'G-CMVP2QRKRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZUfrH51bDdPvRp2qwqR2GTS0WbPtZ3_k',
    appId: '1:670479563518:android:4b425e7a76b73092b343af',
    messagingSenderId: '670479563518',
    projectId: 'cdac-vishing-project',
    storageBucket: 'cdac-vishing-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdisO1mj8Mlhb2j6UYoywnJBDuDIEMFYU',
    appId: '1:670479563518:ios:4062b4ecf2eb7234b343af',
    messagingSenderId: '670479563518',
    projectId: 'cdac-vishing-project',
    storageBucket: 'cdac-vishing-project.appspot.com',
    iosBundleId: 'com.example.cdacDesign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdisO1mj8Mlhb2j6UYoywnJBDuDIEMFYU',
    appId: '1:670479563518:ios:4062b4ecf2eb7234b343af',
    messagingSenderId: '670479563518',
    projectId: 'cdac-vishing-project',
    storageBucket: 'cdac-vishing-project.appspot.com',
    iosBundleId: 'com.example.cdacDesign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvRIv7WNcjhv-g9v-iwvQmhNBBNueq6sM',
    appId: '1:670479563518:web:32ac024cddd2d8cfb343af',
    messagingSenderId: '670479563518',
    projectId: 'cdac-vishing-project',
    authDomain: 'cdac-vishing-project.firebaseapp.com',
    storageBucket: 'cdac-vishing-project.appspot.com',
    measurementId: 'G-10PJX61ZSD',
  );
}
